//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPalkalDrawer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class InsertionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InsertionSettings defaultInstance = ((InsertionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InsertionSettings())));
        
        public static InsertionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FirstGap {
            get {
                return ((int)(this["FirstGap"]));
            }
            set {
                this["FirstGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int RegularGap {
            get {
                return ((int)(this["RegularGap"]));
            }
            set {
                this["RegularGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PointsNumber {
            get {
                return ((int)(this["PointsNumber"]));
            }
            set {
                this["PointsNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LayerName {
            get {
                return ((string)(this["LayerName"]));
            }
            set {
                this["LayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FirstPointLine {
            get {
                return ((int)(this["FirstPointLine"]));
            }
            set {
                this["FirstPointLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FirstPointBore {
            get {
                return ((int)(this["FirstPointBore"]));
            }
            set {
                this["FirstPointBore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E204")]
        public string FirstPointField {
            get {
                return ((string)(this["FirstPointField"]));
            }
            set {
                this["FirstPointField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bMaxPointNum {
            get {
                return ((bool)(this["bMaxPointNum"]));
            }
            set {
                this["bMaxPointNum"] = value;
            }
        }
    }
}
